### ISSUE TITLE
membrane_portaudio_plugin compile error

### ISSUE THREAD

**Issue by puruzio** [membraneframework/membrane_portaudio_plugin#23]
mix deps.compile fails with the following messages. Can you please provide some insights on how to troubleshoot this if there is anything I can try? Thanks.
------------
==> membrane_portaudio_plugin
Bundlex: Building natives: sink, source
could not compile dependency :membrane_portaudio_plugin, "mix compile" failed. You can recompile this dependency with "mix deps.compile membrane_portaudio_plugin", update it with "mix deps.update membrane_portaudio_plugin" or clean it with "mix deps.clean membrane_portaudio_plugin"
** (ErlangError) Erlang error: :enoent
    (elixir 1.12.1) lib/system.ex:1041: System.cmd("pkg-config", ["--cflags", "portaudio-2.0"], [])
    (bundlex 0.5.1) lib/bundlex/toolchain/common/unix.ex:104: Bundlex.Toolchain.Common.Unix.pkg_config/2
    (bundlex 0.5.1) lib/bundlex/toolchain/common/unix.ex:10: Bundlex.Toolchain.Common.Unix.compiler_commands/5
    (bundlex 0.5.1) lib/bundlex/native.ex:104: Bundlex.Native.resolve_native/4
    (bunch 1.3.0) lib/bunch/enum.ex:248: Bunch.Enum.do_try_flat_map/3
    (bundlex 0.5.1) lib/tasks/compile.bundlex.ex:39: Mix.Tasks.Compile.Bundlex.run/1
    (mix 1.12.1) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.1) lib/mix/tasks/compile.all.ex:90: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.12.1) lib/mix/tasks/compile.all.ex:70: Mix.Tasks.Compile.All.compile/4
    (mix 1.12.1) lib/mix/tasks/compile.all.ex:57: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.12.1) lib/mix/tasks/compile.all.ex:35: Mix.Tasks.Compile.All.run/1
    (mix 1.12.1) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.1) lib/mix/tasks/compile.ex:128: Mix.Tasks.Compile.run/1
    (mix 1.12.1) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.1) lib/mix/tasks/deps.compile.ex:172: anonymous fn/2 in Mix.Tasks.Deps.Compile.do_mix/2
    (mix 1.12.1) lib/mix/project.ex:353: Mix.Project.in_project/4
    (elixir 1.12.1) lib/file.ex:1560: File.cd!/2
    (mix 1.12.1) lib/mix/dep.ex:269: Mix.Dep.in_dependency/3
    (mix 1.12.1) lib/mix/tasks/deps.compile.ex:89: anonymous fn/4 in Mix.Tasks.Deps.Compile.compile/2
    (elixir 1.12.1) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2

**Comment by puruzio** [comment]
elixir --version
Erlang/OTP 24 [erts-12.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Elixir 1.12.1 (compiled with Erlang/OTP 24)

MacOS 12.0.1

-----------
% mix deps
...
* membrane_ffmpeg_swresample_plugin (Hex package) (mix)
  locked at 0.10.0 (membrane_ffmpeg_swresample_plugin) 73c61387
  the dependency build is outdated, please run "mix deps.compile"
* membrane_file_plugin 0.7.0 (Hex package) (mix)
  locked at 0.7.0 (membrane_file_plugin) 9efe63c7
  ok
* membrane_mp3_lame_plugin (Hex package) (mix)
  locked at 0.10.0 (membrane_mp3_lame_plugin) 05bbe3fc
  the dependency build is outdated, please run "mix deps.compile"
* membrane_mp3_mad_plugin (Hex package) (mix)
  locked at 0.9.0 (membrane_mp3_mad_plugin) 0b77d40c
  the dependency build is outdated, please run "mix deps.compile"
* membrane_portaudio_plugin (Hex package) (mix)
  locked at 0.10.0 (membrane_portaudio_plugin) b384c38c
  the dependency build is outdated, please run "mix deps.compile"

**Comment by puruzio** [comment]
Thank you. It worked!
